name: CI

on:
  pull_request: {}
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
        with:
          version: 11.20.0
      - uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: 24
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm build
        env:
          ADMIN_GOOGLE_EMAIL: admin@example.com
          NEXT_PUBLIC_KAKAO_MAP_APP_KEY: 7d3e43c57d035f8762f60f374bc1f83f
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: sb_publishable_hrOdkBTCrOKvZCXPWGpUbg_dpZzUSbL
          NEXT_PUBLIC_SUPABASE_URL: https://wdizkhonzlquyxdardeb.supabase.co

  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: supabase/setup-cli@v1
        with:
          version: 2.113.0
      - run: supabase start
      - run: supabase db reset --local
      - run: supabase test db --local
